# Generated by Django 2.0 on 2020-01-22 13:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200122_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_grades',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Grade One'), ('2', 'Grade Two'), ('2', 'Grade Three'), ('2', 'Grade Four')], default=1, max_length=3),
        ),
    ]
