# Generated by Django 2.0 on 2020-01-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_grade'),
        ('freelance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Grade',
            field=models.ForeignKey(default='Grade One', on_delete=django.db.models.deletion.CASCADE, to='users.Grade'),
        ),
    ]
