# Generated by Django 2.0 on 2020-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_auto_20200122_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
