# Generated by Django 2.0 on 2020-01-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_project_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Grade',
            field=models.ForeignKey(default='Grade-One', on_delete=django.db.models.deletion.CASCADE, to='users.Grade'),
        ),
    ]
