# Generated by Django 2.0 on 2020-01-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0004_remove_project_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
